version: '3'

services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: 'freelance'
      MYSQL_USER: 'freelance'
      MYSQL_PASSWORD: 'freelance'
      MYSQL_ROOT_PASSWORD: 'freelance'
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 'freelance'
      MYSQL_USER: 'freelance'
      MYSQL_PASSWORD: 'freelance'
    restart: always
    ports:
      - 8081:80
    expose:
      - 8081

volumes:
  dbdata: